### PR TITLE
#15 fixed SipServletMessage.addHeader handles transport badly

### PR DESCRIPTION
**Pull request by xhoaluu**
Please help me toreview the fix, I have run the regression test, the result is the same result as jenkin

### CODE REVIEW

**Comment by deruelle** [comment]
@xhoaluu did you run the whole testsuite with ant cc-buildloop to ensure there is no regression on other tests ?

**Comment by xhoaluu** [comment]
Not sure that I understand what you are saying but after pulling latest code from baseline, I used command : mvn clean install to run the test.

**Comment by deruelle** [comment]
So this SIP Stack is a reference implementation of the JAIN SIP Specification JSR 32.

It contains 2 different testsuite the TCK at https://github.com/RestComm/jain-sip/tree/master/src/test/tck and the extended testsuite (that covers more tests not part of the TCK) ie https://github.com/RestComm/jain-sip/tree/master/src/test/unit/gov/nist/javax/sip and https://github.com/RestComm/jain-sip/tree/master/src/test/gov/nist/javax/sdp/parser.

To run all tests of the TCK and testsuite as done on the CI job at https://mobicents.ci.cloudbees.com/job/JAIN-SIP you need to run from the root directory the ant script target cc-buildloop with the following command:

`ant cc-buildloop`

This will validate that all tests are still passing and your changes didn't introduce any regressions in the testsuite and TCK

**Comment by xhoaluu** [comment]
Now I got your point. I just ran the regression test on sip-servlet.

**Comment by xhoaluu** [comment]
In legacy code, they have been intending to code the feature as after ';' all the things will be used as header parameter and not uri parameter, If we want to include uri parameter into header address, we need to put it inside of '< >'. In my point of view, I don't thing this issue is a bug.

So if we are thinking this is the bug then I have 2 options:
1/ change the behavior of jain-sip to accept that all parameters after ';' in the value of header will be used as uri parameter. Ex:
response.addHeader("Contact", "sip:abc@domain.com; param1=1; param2=2"); the result will be:
Contact:<sip:abc@domain.com; param1=1; param2=2> 
2/ create a known uri parameter list in the code. if the param name is in the list, then it will be used as uri parameter instead of header parameter.

wdyt?

**Comment by deruelle** [comment]
Did you confirm your point of view with the RFC 3261 ?

**Comment by jaimecasero** [comment]
we nned to be carefull on URI versus header parameters. Ass @xhoaluu  mentioned, angled brackets are necessary on URI to include params, so they are separated from the rest of the header...

**Comment by xhoaluu** [comment]
So Could we close this issue with no action ? Because I think jain-sip is already providing us the way to include uri parameter and this way is different with the way to include header parameter.

**Comment by deruelle** [comment]
@xhoaluu did you check the RFC on what is right or wrong ?

**Comment by xhoaluu** [comment]
Hi @deruelle ,

I have checked with RFC, RFC does not show how the api handle for the case. it just state definition of uri parameter and header parameter. Base on that I can sure that the api is working well.
If I want to create a header name"Contact" with 2 uri parameters and 1 header parameter like this: Contact:<sip:abc@domain.com;transport=tcp, ttl=15>; expire=3600

 we just simply using api:
response.addHeader("Contact","<sip:abc@domain.com;transport=tcp, ttl=15>; expire=3600" );

Jain sip will create the really exact contact header content is like what we want. we can enhance for jain-sip that create a list of known uri parameters then if the designers put uri parameter in wrong place where is the place of header parameter then jain sip will move the uri parameter to right place.

**Comment by deruelle** [comment]
I'll let @jaimecasero decides if he wants to close this one or not.

**Comment by xhoaluu** [comment]
Yes, for sure @deruelle. I have looked through the issues related to sip-servlet but they are not clear about requirement or I really don't know the issue is already closed or not to pick one up to work. 

Do you have any issue that I can take for sip-servlet or Jain-sip?

**Comment by jaimecasero** [comment]
Some jain-sip issues you may try...
https://github.com/RestComm/jain-sip/issues/105 -> header parsing,should be
easy to implement and test
https://github.com/RestComm/jain-sip/issues/57 -> new RFC to implement
message compression( long task)
https://github.com/RestComm/jain-sip/issues/58 -> Review sip state machine
to allow this new scenario (complex task)

**Comment by xhoaluu** [comment]
Long time no see @jaimecasero ,

I would love to pick #105 to work.

**Pull request closed without merging**
