### PR TITLE
fixes https://github.com/RestComm/jain-sip/issues/85

### PR DESCRIPTION
**Pull request by jaimecasero**

### CODE REVIEW

**Comment by deruelle** [comment]
@jaimecasero was it verified to be working ? Is it in a state where it can now be merged ?

**Comment by jaimecasero** [comment]
Yes it was, but it changes the default cipher suites compared to the old
version, so Im afraid about breaking some app including Restcomm becuase of
this. We may change the default cipher suites in Stack with the ones the
previous code was using ( default ones by JVM...)

**Comment by deruelle** [comment]
why don't you make the default cipher the same as before to keep backward compatibility ?
New ones are configurable anyway so we can check the impact at RestComm by specifying the right value in the property file.

**Comment by jaimecasero** [comment]
It makes sense. Just the Stack current default ones are used if factory is
set to old IO, instead of NIO. I guess this was missing during NIO
migration, and now its been a long time, and we dont know how will impact
different apps...

**Comment by jaimecasero** [comment]
I will check if default JVM ones includes the current stack default ones, in that case the potential issues would minimized. https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/SipStackImpl.java#L657

**Comment by deruelle** [comment]
what ciphers were used for NIO if they were not specified ?
I think that's fine still as apps will do testing before updating anyway and will be able to choose the ciphers through the property if anything goes wrong.

**Comment by jaimecasero** [comment]
Previous change, NIO default ones were from JVM (depends on JVM version)

After change the default ones comes from Stack https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/SipStackImpl.java#L657

**Comment by jaimecasero** [comment]
From https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#footnote2-1

TLS_RSA_WITH_AES_128_CBC_SHA -> enabled from 1.4.1
SSL_RSA_WITH_3DES_EDE_CBC_SHA -> enabled from 1.4
TLS_DH_anon_WITH_AES_128_CBC_SHA -> enabled from 1.4.1
SSL_DH_anon_WITH_3DES_EDE_CBC_SHA -> enabled from 1.4

Based on this, I think is safe to set the default stack cipher suites to the ones coming from the JVM, and just in case specific suites are provided from property file, use different ones...

**Comment by jaimecasero** [comment]
Since the default MessageProcessorFactory is still the old one, I would suggests to keep cipherSuites default as they are. The new configuration property allows to specify the suites you need, so it will be easy to fix any integration issue resulting from this change for the NIO implementations...

**Pull request merged**
